curl -X PATCH http://localhost:8080/clientes
-H "Content-Type: application/json" 
-d '{
  "id":"4",
  "name":"Cliente 6 - Nuevo",
  "username":"cliente6nuevo",
  "password":"123456789"
}'

curl -X PATCH http://localhost:8080/clientes -H "Content-Type: application/json"  -d '{ "id":"4", "name":"Cliente 6 - Nuevo"}'
